import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';

class FirebaseConfigErrorScreen extends StatelessWidget {
  const FirebaseConfigErrorScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Configuration Required')),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              const Text(
                'Firebase is not configured for this platform.',
                textAlign: TextAlign.center,
                style: TextStyle(fontSize: 18),
              ),
              const SizedBox(height: 12),
              Text(
                kIsWeb
                    ? 'On web, initialize Firebase with options generated by FlutterFire.'
                    : 'Please check your Firebase configuration.',
                textAlign: TextAlign.center,
              ),
            ],
          ),
        ),
      ),
    );
  }
}
