// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCna0cvxzRAzzoj7OOMJBZk0PrFklt0Q8o',
    appId: '1:291106879361:android:36d9e9a69ea9f6a8a71a80',
    messagingSenderId: '291106879361',
    projectId: 'kalakart-9b45e',
    storageBucket: 'kalakart-9b45e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUT5j0mEKQx47zRqWNwKMeOf7UNMLnJ1c',
    appId: '1:1066238839896:ios:b9dd0410a94b8c80928e2d',
    messagingSenderId: '1066238839896',
    projectId: 'ecommerce-app-aaa73',
    storageBucket: 'ecommerce-app-aaa73.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAdminApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2uS4oPH227ggDyXXEMrw6JinOJ82xtLg',
    appId: '1:291106879361:web:2a2a71ff9fad9a05a71a80',
    messagingSenderId: '291106879361',
    projectId: 'kalakart-9b45e',
    authDomain: 'kalakart-9b45e.firebaseapp.com',
    storageBucket: 'kalakart-9b45e.firebasestorage.app',
    measurementId: 'G-RWW822E9RB',
  );

}